<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ChromeForTesting" Version="143.0.7499.42045" />
        <PackageReference Include="CliWrap" Version="3.10.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1"/>
        <PackageReference Include="NUnit" Version="4.4.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="6.0.0"/>
        <PackageReference Include="NUnit.Analyzers" Version="4.11.2"/>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
    </ItemGroup>

</Project>
