name: Test Latest Nuget Package
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x64
      fail-fast: false
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Update to latest ChromeForTesting Nuget
      working-directory: ChromeForTesting
      run: dotnet add ChromeForTesting.Tests package ChromeForTesting

    - name: Run Tests
      working-directory: ChromeForTesting
      run: dotnet test ChromeForTesting.sln
